[tool.poetry]
name = "incubator"
version = "0.1.0"
description = ""
authors = ["Clemens Winter <clemenswinter1@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
# TODO: when griddly APIs support everything thats needed, can change this from a local dependency to whats on pypi
griddly = {path = "../Griddly/python", develop=true, optional = true}

[tool.poetry.dev-dependencies]
black = "^21.11b1"
pytest = "^6.2.5"
mypy = "^0.910"
entity_gym = {path = "entity_gym", develop = true}
rogue_net = {path = "rogue_net", develop = true}
enn_ppo = {path = "enn_ppo", develop = true}

[tool.poetry.extras]
griddly = ["griddly"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
